### ISSUE TITLE
Can't get it to run, get TypeError: argument 1 must be str, not PosixPath

### ISSUE THREAD

**Issue by aquilesC** [syegulalp/folio#1]
I would really like to give Folio a spin, and if time allows help it grow. But I couldn't make it run. After cloning and insalling the dependencies in a clean environment, got the following error:

```bash
$ python folio
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "folio/__main__.py", line 78, in <module>
    import routes
  File "folio/routes.py", line 15, in <module>
    from models import (
  File "folio/models.py", line 26, in <module>
    db.connect()
  File "/home/aquiles/venvs/folio/lib/python3.6/site-packages/peewee.py", line 3026, in connect
    self._state.set_connection(self._connect())
  File "/home/aquiles/venvs/folio/lib/python3.6/site-packages/peewee.py", line 3362, in _connect
    isolation_level=None, **self.connect_params)
TypeError: argument 1 must be str, not PosixPath
```

**Comment by aquilesC** [comment]
This is solved using Python 3.7 (by default you get 3.6 on Linux)
